name: Angular Lint, Build and Test Angular Client

on:
  push:
    branches: [ main ]
    paths:
    - 'angular-client'
    - '.github/workflows/buildAndTestAngular.yml'
  pull_request:
    branches: [ main ]
    paths:
    - 'angular-client'
    - '.github/workflows/buildAndTestAngular.yml'
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        
      - name: Run npm install
        run: |
          cd angular-client
          npm install
        
      - name: Lint
        run: |
          cd angular-client 
          npm run lint

      - name: Build
        run: |
          cd angular-client 
          npm run build

      - name: Test
        run: |
          cd angular-client 
          npm run test-headless

      - name: Build-prod
        run: |
          cd angular-client 
          npm run build-prod
    
